package com.parship.propertree.ui;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.server.Sizeable;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalSplitPanel;
import com.vaadin.ui.MenuBar;
import com.vaadin.ui.VerticalLayout;

public class MainPanelUI extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private VerticalLayout verticalLayout_1;
	@AutoGenerated
	private HorizontalSplitPanel horizontalSplitPanel_1;
	@AutoGenerated
	private EditPanelUI editPanelUI_1;
	@AutoGenerated
	private NavigationUI navigationUI_1;
	@AutoGenerated
	private MenuBar menuBar_1;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public MainPanelUI() {
		buildMainLayout();
		setCompositionRoot(mainLayout);
		
		// CUSTOM CODE START
		
		horizontalSplitPanel_1.setSplitPosition(200, Sizeable.UNITS_PIXELS);
		
		// About
		MenuBar.MenuItem about = menuBar_1.addItem("Propertree", null);
		about.addItem("About", null);
		about.addItem("License", null);
		about.addItem("Website", null);
		about.addItem("Team", null);
		
		// User name
		// TODO username
		MenuBar.MenuItem user = menuBar_1.addItem("Marc", null);
		user.addItem("User Settings", null);
		user.addItem("Logout", null);
		menuBar_1.setAutoOpen(false);
		
		// CUSTOM CODE END
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// verticalLayout_1
		verticalLayout_1 = buildVerticalLayout_1();
		mainLayout.addComponent(verticalLayout_1, "top:0.0px;left:0.0px;");
		
		return mainLayout;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_1() {
		// common part: create layout
		verticalLayout_1 = new VerticalLayout();
		verticalLayout_1.setImmediate(false);
		verticalLayout_1.setWidth("100.0%");
		verticalLayout_1.setHeight("100.0%");
		verticalLayout_1.setMargin(false);
		
		// menuBar_1
		menuBar_1 = new MenuBar();
		menuBar_1.setImmediate(false);
		menuBar_1.setWidth("100.0%");
		menuBar_1.setHeight("-1px");
		verticalLayout_1.addComponent(menuBar_1);
		
		// horizontalSplitPanel_1
		horizontalSplitPanel_1 = buildHorizontalSplitPanel_1();
		verticalLayout_1.addComponent(horizontalSplitPanel_1);
		verticalLayout_1.setExpandRatio(horizontalSplitPanel_1, 1.0f);
		
		return verticalLayout_1;
	}

	@AutoGenerated
	private HorizontalSplitPanel buildHorizontalSplitPanel_1() {
		// common part: create layout
		horizontalSplitPanel_1 = new HorizontalSplitPanel();
		horizontalSplitPanel_1.setImmediate(false);
		horizontalSplitPanel_1.setWidth("100.0%");
		horizontalSplitPanel_1.setHeight("100.0%");
		
		// navigationUI_1
		navigationUI_1 = new NavigationUI();
		navigationUI_1.setImmediate(false);
		navigationUI_1.setWidth("100.0%");
		navigationUI_1.setHeight("100.0%");
		horizontalSplitPanel_1.addComponent(navigationUI_1);
		
		// editPanelUI_1
		editPanelUI_1 = new EditPanelUI();
		editPanelUI_1.setImmediate(false);
		editPanelUI_1.setWidth("100.0%");
		editPanelUI_1.setHeight("100.0%");
		horizontalSplitPanel_1.addComponent(editPanelUI_1);
		
		return horizontalSplitPanel_1;
	}

}
